### ISSUE TITLE
Implement search feature

### ISSUE THREAD

**Issue by hafen** [ki-tools/set#1]
This is the magnifying glass in the top right corner. To get it implemented, I need a clear understanding of how the interactions with it will work, either a description or a mockup of how this will work (@chad-cognition).

**Comment by chad-cognition** [comment]
This is super old from some of the original wireframes. And, I can't find a more recent example (which means there probably isn't one). Here's what I was originally thinking for search. We can use this to talk though it. But, it would likely be beneficial to make some update mockups of some key states. We can discuss. 
https://invis.io/G8QO8F5DTBK#/231979760_Global_Search_2

**Comment by hafen** [comment]
This has been implemented and is live on the dev site. @chad-cognition please take a look.

<img width="557" alt="image" src="https://user-images.githubusercontent.com/1275592/55043762-d6733600-4ff4-11e9-8d55-211223a9108a.png">

**Comment by chad-cognition** [comment]
I think this works well! The one issue I found was if you add an event that falls outside of the current range of view, it doesn't look like anything happened.

I think the descriptions of how many events are before and after discussed in another thread will help with this as an initial point. So, you'd be able to see a little prompt that appears on the side that says, "<- 1 event", as part of feedback.
