### ISSUE TITLE
Build Contact Pages/Forms

### ISSUE THREAD

**Issue by chad-cognition** [ki-tools/set#11]
Mockups are here: https://invis.io/BAPLMK56G5U#/371920657_SET_-_Contact_Landing

**Comment by chad-cognition** [comment]
These forms won't actually be functional until it's on a real host.

**Comment by hafen** [comment]
These have been implemented and are live. The only thing missing is actually firing off an email. There are a number options for this, but we might want to wait on figuring out where this will be hosted to figure that out.

**Comment by hafen** [comment]
These have been implemented and are live. The only thing missing is actually firing off an email. There are a number options for this, but we might want to wait on figuring out where this will be hosted to figure that out.

Closing even though the email issue remains. That can be part of #10.

**Comment by chad-cognition** [comment]
EmailJS.com (free for up to 200)
