### ISSUE TITLE
Add sitewide footer

### ISSUE THREAD

**Issue by chad-cognition** [ki-tools/set#12]
- [ ] RYAN: Add footer to main visualization page and rest of site; This exists in the mockups
- [ ] RYAN: Link to Terms of Service/Privacy - https://www.gatesfoundation.org/Privacy-and-Cookies-Notice
- [ ] RYAN: Link to Terms of Use - https://www.gatesfoundation.org/Terms-of-Use

**Comment by hafen** [comment]
Links have been added and footer is present on all pages.
