### ISSUE TITLE
Risk Data Labeling

### ISSUE THREAD

**Issue by chad-cognition** [ki-tools/set#14]
ACTION: Chad to mockup additional labeling

**Comment by chad-cognition** [comment]
Hi @hafen,

What do you think of this additional labeling for the risk data? To help give it additional context and handling the unit labels?
https://projects.invisionapp.com/d/main#/console/16239809/376992338/preview

Thanks,
Chad

**Comment by hafen** [comment]
@chad-cognition before I go any further on this, I just want to make sure the arrangement of the categories from left to right should indeed be Intervention -> Risk Factor -> Pathogenesis -> Health Outcome. It is the reverse in the app right now. It will take some effort to change, so I wanted to double check.

**Comment by hafen** [comment]
Forgot to close this. I implemented this last week. @chad-cognition if you notice any issues let me know.
