### ISSUE TITLE
Homepage: Mockup wider version with optimized photo

### ISSUE THREAD

**Issue by chad-cognition** [ki-tools/set#15]

**Comment by chad-cognition** [comment]
![GA1276522_JA140333-extended](https://user-images.githubusercontent.com/47614620/62075954-54418b00-b1fb-11e9-81d4-43685b3a5015.jpg)

@hafen: Here's an extended image for the homepage. This should hopefully be a bit better to avoid the text colliding with a dark area. But, we can still refine further if needed. Thanks!

**Comment by hafen** [comment]
I have put this in and I think it's working. @chad-cognition please take a look.
