### ISSUE TITLE
Keep track of state

### ISSUE THREAD

**Issue by hafen** [ki-tools/set#2]
Either actively track the state in the URL (using router or hash) or implement the link icon in the top right of the header, which when clicked will provide a shareable URL that will recreate the current state when entered in a new browser window.

**Comment by hafen** [comment]
This has been implemented. State is tracked in the URL. If we want we can hide the URL and only make it available when the user clicks the link icon, but this is good enough for now.

**Comment by chad-cognition** [comment]
Awesome! This appears to work for me. Next is adding it as a button in the navigation to provide the affordance that this is possible.
