### ISSUE TITLE
Variables Drop Down: Hover states for category buttons to give interaction affordance

### ISSUE THREAD

**Issue by chad-cognition** [ki-tools/set#21]

**Comment by chad-cognition** [comment]
@hafen: I mocked up hovers states for this. You can see it in the 'Central Nervous' and 'Sensory Organs/Peripheral Nervous' buttons. See here: https://invis.io/BAPLMK56G5U#/343149598_Use_Case_2_-_Breastfeed_1_Copy_15

**Comment by hafen** [comment]
@chad-cognition I don't see anything change when I hover or click on these buttons in the mockup.
