### ISSUE TITLE
Update name throughout the site

### ISSUE THREAD

**Issue by chad-cognition** [ki-tools/set#44]

**Comment by chad-cognition** [comment]
@hafen: I've updated this in the mockups. 

Key areas to change the name:
- Global header (https://invis.io/BAPLMK56G5U#/395288665_SET_Home_Copy_2)
- On homepage main hero image area (https://invis.io/BAPLMK56G5U#/395288665_SET_Home_Copy_2) 
- Find and replace on Methodology page (for both the name and the acronym) (https://invis.io/BAPLMK56G5U#/372076717_SET_-_Methodology)

**Comment by hafen** [comment]
Fixed. On the methodology page I took the liberty to replace "The TELEO" with "TELEO". For example, "Development of the TELEO began..." was changed to "Development of TELEO began...". That sounded more natural. Happy to change it back.
